[package]
name = "clue_core"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true
readme = "./README.md"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
lazy_static = "1.4.0"
ahash.workspace = true
clap.workspace = true
rpmalloc = {version = "0.2.2", optional = true}

[features]
default = ["rpmalloc"]
bench = ["rpmalloc"]