[package]
name = "clue_wasm"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme = "./README.md"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde = "1.0.159"
wasm-bindgen = "0.2.84"
clue_core = { path = "../core", version = "3.2.0-indev", default-features = false }
serde-wasm-bindgen = "0.5.0"
