[package]
name = "clue_macros"
version = "1.0.0-beta"

[lib]
proc-macro = true

[dependencies]
litrs = {version = "0.2.3", optional = true}
toml = {version = "0.5.9", optional = true}

[features]
map = ["litrs"]
version = ["toml"]