name: "Build rust for musl libc"
description: "Build rust binaries for musl libc using void linux and docker"
inputs:
  name:
    description: "Name of the crate"
    required: true
runs:
  using: "docker"
  image: "markosth09/voidlinux-rust-nightly-cross:latest"
  env:
    CRATE_NAME: ${{ inputs.name }}
