name: Bench
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          toolchain: stable
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Test release build
        run: cargo bench
