name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  cratesio-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Publish core
        run: cargo publish -p clue_core
      - name: Publish cli
        run: cargo publish -p clue
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: clue
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
